name: hspec-glitter
version: 0.1.0
synopsis: A git-based hspec golden test
maintainer: Christian Gram Kalhauge <christiankalhauge@gmail.com>
category: Testing

ghc-options: -Wall -fno-warn-incomplete-uni-patterns 

dependencies:
  - base >= 4.9 && < 5
  - hspec-core
  - text
  - bytestring
  - attoparsec
  - typed-process
  - filepath
  - directory

library:
  source-dirs: src

tests:
  hspec-glitter-test: 
    source-dirs: test/src
    main: Main.hs
    dependencies:
      - hspec
      - hspec-discover
      - hspec-glitter
      - directory
      - filepath
      - typed-process
