name: hspec-glitter
version: 0.1.0
synopsis: A git-based hspec golden test
maintainer: Christian Gram Kalhauge <christiankalhauge@gmail.com>
category: Testing

ghc-options: -Wall -fno-warn-incomplete-uni-patterns 

dependencies:
  - base >= 4.9 && < 5
  - hspec-core
  - text
  - bytestring
  - typed-process
  - filepath
  - directory
  - HUnit

library:
  source-dirs: src
